---

  - name: Enable Firewall
    service:
      name: firewalld
      state: started
      enabled: yes
    tags:
      - ssh
      - firewall

  - name: Configure Firewall
    firewalld:
      port: "{{ item.port }}/item.proto"
      permanent: yes
      state: enabled
    with_items:
      - { port: '{{ ssh_port }}', proto: 'tcp' }
      - { port: '1194', proto: 'tcp' }
    notify:
      - restart firewalld
    tags:
      - ssh
      - firewall